# Set to true to add assignees to pull requests
addAssignees: true

# A list of assignees, overrides reviewers if set
assignees:
  - wbooth

numberOfAssignees: 0

# A list of keywords to be skipped the process that add reviewers if pull requests include it
skipKeywords:
  - wip
